//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia.Core.Messages.ContaMessages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContaMsgsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContaMsgsResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialMedia.Core.Messages.ContaMessages.ContaMsgsResource", typeof(ContaMsgsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário da conta deve ser maior de idade..
        /// </summary>
        internal static string ContaDataNascimentoMinAge {
            get {
                return ResourceManager.GetString("ContaDataNascimentoMinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Nascimento não pode ser vazio..
        /// </summary>
        internal static string ContaDataNascimentoNotEmpty {
            get {
                return ResourceManager.GetString("ContaDataNascimentoNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail inválido..
        /// </summary>
        internal static string ContaEmailInvalid {
            get {
                return ResourceManager.GetString("ContaEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail deve ter no máximo 150 caracteres..
        /// </summary>
        internal static string ContaEmailMaxLength {
            get {
                return ResourceManager.GetString("ContaEmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail não pode ser vazio..
        /// </summary>
        internal static string ContaEmailNotEmpty {
            get {
                return ResourceManager.GetString("ContaEmailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome completo deve ter no máximo 150 caracteres..
        /// </summary>
        internal static string ContaNomeCompletoMaxLength {
            get {
                return ResourceManager.GetString("ContaNomeCompletoMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome completo não pode ser vazio..
        /// </summary>
        internal static string ContaNomeCompletoNotEmpty {
            get {
                return ResourceManager.GetString("ContaNomeCompletoNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta não existe..
        /// </summary>
        internal static string ContaNotExist {
            get {
                return ResourceManager.GetString("ContaNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha inválida..
        /// </summary>
        internal static string ContaSenhaInvalid {
            get {
                return ResourceManager.GetString("ContaSenhaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha deve ter no máximo 15 caracteres..
        /// </summary>
        internal static string ContaSenhaMaxLength {
            get {
                return ResourceManager.GetString("ContaSenhaMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha não pode ser vazia..
        /// </summary>
        internal static string ContaSenhaNotEmpty {
            get {
                return ResourceManager.GetString("ContaSenhaNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone deve ter no máximo 20 caracteres..
        /// </summary>
        internal static string ContaTelefoneMaxLength {
            get {
                return ResourceManager.GetString("ContaTelefoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone não pode ser vazio..
        /// </summary>
        internal static string ContaTelefoneNotEmpty {
            get {
                return ResourceManager.GetString("ContaTelefoneNotEmpty", resourceCulture);
            }
        }
    }
}
